### ISSUE TITLE
Evaluating on Referit3D Nr3D and Sr3D

### ISSUE THREAD

**Issue by eslambakr** [zlccccc/3DVG-Transformer#5]
Dears,

Thanks for sharing your code base. But I can't find the code related to Nr3D/Sr3D training and evaluation.

More importantly, regarding the results reported into Table 2, I think you have followed InstanceRefer configuration where they use the GT boxes as an input instead of the whole scene (https://github.com/CurryYuan/InstanceRefer/issues/4) to be able to compare against other methods, Is that correct?

Thanks in advance!

**Comment by zlccccc** [comment]
Yes. we follow the official Referit3D setting (based on their implementation) to use the GT boxes as an input instead of the whole scene for a fair comparison.
To be specific, just simply adding a few layers of coordinate-guided self-attention before their fusion stage could lead to great results. Since the implementation is very simple and straightforward (and some codebases with higher results have been released recently), we do not release our codes.

**Comment by eslambakr** [comment]
Perfect!
Thank you very much for your prompt response, Much appreciated!
